export const contracts = [
    {
        id: 'META-001',
        guarantee: 'Every registered contract has an executable test reference and a blocking job',
        source: 'test/unit/contracts.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-001',
        guarantee: 'Nuxt discovers the root files.config.ts and initializes its declared storage',
        source: 'test/nuxt/suite.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'CFG-002',
        guarantee: 'Unnamed access is exclusive to a single-storage configuration',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-003',
        guarantee: 'Production initialization failures never use devStorage as fallback',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-004',
        guarantee: 'Development overrides preserve base plugins and native hooks',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-005',
        guarantee: 'Provider options live under config and accept synchronous runtime resolvers',
        source: 'test/unit/config.test.ts',
        job: 'typecheck',
    },
    {
        id: 'CFG-006',
        guarantee: 'Provider initialization failure never attempts HTTP or another provider',
        source: 'test/unit/no-fallback.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-007',
        guarantee: 'Native operation failure never switches storage or wraps its error',
        source: 'test/unit/no-fallback.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-008',
        guarantee: 'Unknown development override names fail before provider construction',
        source: 'test/unit/no-fallback.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-009',
        guarantee: 'Generation selects only active-mode providers without resolving runtime credentials',
        source: 'test/unit/generation.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-010',
        guarantee: 'Non-development prepare cannot overwrite a running development plugin',
        source: 'test/unit/generation.test.ts',
        job: 'unit',
    },
    {
        id: 'API-001',
        guarantee: 'useServerFiles synchronously returns the cached Files client',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'API-002',
        guarantee: 'Named storage preserves native Files methods and plugin extensions',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'API-003',
        guarantee: 'Single storage preserves its plugin extensions',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-001',
        guarantee: 'Actual generated consumer types preserve native and plugin surfaces',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-002',
        guarantee: 'Unknown storage names fail compilation with an argument type error',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-003',
        guarantee: 'Unknown adapter names fail compilation',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-004',
        guarantee: 'devStorage cannot replace plugins',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-005',
        guarantee: 'devStorage cannot replace hooks',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-006',
        guarantee: 'Standalone Nitro generates single/named storage and major-specific hook declarations',
        source: 'test/nitro/suite.ts',
        job: 'test-nitro3',
    },
    {
        id: 'TYPE-007',
        guarantee: 'The removed default selector fails compilation',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-008',
        guarantee: 'Development overrides are limited to declared storage names',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-009',
        guarantee: 'Providers with required options require config',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-010',
        guarantee: 'Provider-specific options are rejected outside config',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-011',
        guarantee: 'Async provider config resolvers fail compilation',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-012',
        guarantee: 'Multiple storages require a name at every access',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-013',
        guarantee: 'Named FilesRegistry access requires a storage name',
        source: 'test/unit/config.test.ts',
        job: 'typecheck',
    },
    {
        id: 'ENV-001',
        guarantee: 'Native environment keys and aliases take precedence over NUXT aliases',
        source: 'test/unit/environment.test.ts',
        job: 'unit',
    },
    {
        id: 'ENV-002',
        guarantee: 'Only keys declared by the selected provider may be injected',
        source: 'test/unit/environment.test.ts',
        job: 'unit',
    },
    {
        id: 'ENV-003',
        guarantee: 'Temporary aliases are removed on success and failure',
        source: 'test/unit/environment.test.ts',
        job: 'unit',
    },
    {
        id: 'ENV-004',
        guarantee: 'Nested synchronous construction keeps temporary aliases until the outer call returns',
        source: 'test/unit/environment.test.ts',
        job: 'unit',
    },
    {
        id: 'RUNTIME-001',
        guarantee: 'Repeated access returns one synchronously constructed storage instance',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'RUNTIME-002',
        guarantee: 'Named storages construct and cache independently',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'RUNTIME-003',
        guarantee: 'Failed construction is not cached and can be retried',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'RUNTIME-004',
        guarantee: 'Async and circular config resolution fail explicitly',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'HOOK-001',
        guarantee: 'User and Nitro bridge hooks run in order; rejection does not break operations',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'ERR-001',
        guarantee: 'Invalid config, unknown names, and missing names have stable integration codes',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'ERR-002',
        guarantee: 'Native FilesError identity and code survive initialization failures',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'NUXT-001',
        guarantee: 'Real Nuxt runtime routes receive the configured Files instances',
        source: 'test/nuxt/suite.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'NUXT-002',
        guarantee: 'Native Vue composable auto-imports compile and build',
        source: 'test/nuxt/vue.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'NITRO-001',
        guarantee: 'Nitro v2/v3 prepare, typecheck, build, and serve the Files route',
        source: 'test/nitro/suite.ts',
        job: 'test-nitro2',
    },
    {
        id: 'DEV-001',
        guarantee: 'Production, module opt-out, and disabled Nuxt DevTools disable the DevFrame',
        source: 'test/nuxt/devtools.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'DEV-002',
        guarantee: 'DevTools v3 registers a single iframe for the shared UI',
        source: 'test/nuxt/devtools.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'DEV-003',
        guarantee: 'DevTools v4 registers the native DevFrame-ready host',
        source: 'test/nuxt/devtools.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'DEV-004',
        guarantee: 'The development host serves the shared UI and the actual configured registry snapshot',
        source: 'test/nuxt/nuxt4-devframe.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'BUNDLE-001',
        guarantee: 'Server-only Nuxt does not include files-sdk/vue',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'BUNDLE-002',
        guarantee: 'Production excludes DevFrame and development host code',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'BUNDLE-003',
        guarantee: 'fs consumers include only the fs provider entrypoint and no external cloud SDK packages',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'BUNDLE-004',
        guarantee: 'A versioning-only import excludes unrelated built-in plugin entrypoints',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'BUNDLE-005',
        guarantee: 'Standalone Nitro excludes Nuxt Kit, DevTools, and Files Vue runtime',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'BUNDLE-006',
        guarantee: 'Deployment sizes are measured; established Nuxt output budgets are enforced',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'SEC-001',
        guarantee: 'Dummy secrets are absent from production and generated outputs',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'SEC-002',
        guarantee: 'DevFrame snapshots contain only safe metadata and diagnostics',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'SEC-003',
        guarantee: 'The packed artifact contains no dummy secret',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'PKG-001',
        guarantee: 'Required JavaScript and declaration entrypoints are packed',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'PKG-002',
        guarantee: 'The tarball contains only distribution files and public package metadata',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'PKG-003',
        guarantee: 'Exports and dependency/optional-peer boundaries are explicit',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'PKG-004',
        guarantee:
            'Fresh Nuxt/Nitro consumers install the tarball, typecheck, build, and run with bundle/security boundaries intact',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'PKG-005',
        guarantee: 'publint and ATTW validate the actual tarball',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'DOCS-001',
        guarantee: 'Canonical fixture examples and native public types compile against generated declarations',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'DOCS-002',
        guarantee: 'Packed public APIs, generated auto-imports, and configuration fields retain hover documentation',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'REL-001',
        guarantee: 'Consumer verification leaves the release tarball SHA-256 unchanged',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'REL-002',
        guarantee: 'ci-ok directly gates every blocking job, and release verifies the tarball before publishing',
        source: 'test/unit/contracts.test.ts',
        job: 'unit',
    },
]
