export const contracts = [
    {
        id: 'META-001',
        guarantee: 'Every registered contract has an executable test reference and a blocking job',
        source: 'test/unit/contracts.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-001',
        guarantee: 'Nuxt discovers the root files.config.ts and initializes its declared storage',
        source: 'test/nuxt/suite.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'CFG-002',
        guarantee: 'Explicit defaults work and ambiguous unnamed runtime access fails',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-003',
        guarantee: 'Production initialization failures never use devStorage as fallback',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-004',
        guarantee: 'Development overrides preserve base plugins and native hooks',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-005',
        guarantee: 'Single, named-default, and ambiguous storage types match default selection',
        source: 'test/unit/config.test.ts',
        job: 'typecheck',
    },
    {
        id: 'CFG-006',
        guarantee: 'Provider initialization failure never attempts HTTP or another provider',
        source: 'test/unit/no-fallback.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-007',
        guarantee: 'Native operation failure never switches storage or wraps its error',
        source: 'test/unit/no-fallback.test.ts',
        job: 'unit',
    },
    {
        id: 'CFG-008',
        guarantee: 'Unknown default and development override names fail before provider initialization',
        source: 'test/unit/no-fallback.test.ts',
        job: 'unit',
    },
    {
        id: 'API-001',
        guarantee: 'useServerFiles returns the cached initialization Promise',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'API-002',
        guarantee: 'Named storage preserves native Files methods and plugin extensions',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'API-003',
        guarantee: 'Explicit default storage preserves its plugin extensions',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-001',
        guarantee: 'Actual generated consumer types preserve native and plugin surfaces',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-002',
        guarantee: 'Unknown storage names fail compilation with an argument type error',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-003',
        guarantee: 'Unknown adapter names fail compilation',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-004',
        guarantee: 'devStorage cannot replace plugins',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-005',
        guarantee: 'devStorage cannot replace hooks',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-006',
        guarantee: 'Standalone Nitro generates storage, default/plugin, and major-specific hook declarations',
        source: 'test/nitro/suite.ts',
        job: 'test-nitro3',
    },
    {
        id: 'TYPE-007',
        guarantee: 'Configuration defaults must name a declared storage',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'TYPE-008',
        guarantee: 'Development overrides are limited to declared storage names',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'ENV-001',
        guarantee: 'Native environment keys and aliases take precedence over NUXT aliases',
        source: 'test/unit/environment.test.ts',
        job: 'unit',
    },
    {
        id: 'ENV-002',
        guarantee: 'Only keys declared by the selected provider may be injected',
        source: 'test/unit/environment.test.ts',
        job: 'unit',
    },
    {
        id: 'ENV-003',
        guarantee: 'Temporary aliases are removed on success and failure',
        source: 'test/unit/environment.test.ts',
        job: 'unit',
    },
    {
        id: 'ENV-004',
        guarantee: "Concurrent bridge users cannot observe another initialization's cleanup",
        source: 'test/unit/environment.test.ts',
        job: 'unit',
    },
    {
        id: 'RUNTIME-001',
        guarantee: '100 concurrent calls initialize one shared storage instance',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'RUNTIME-002',
        guarantee: 'Multiple storages initialize independently, including partial failure',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'RUNTIME-003',
        guarantee: 'Failed initialization is evicted and can be retried',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'HOOK-001',
        guarantee: 'User and Nitro bridge hooks run in order; rejection does not break operations',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'ERR-001',
        guarantee: 'Invalid config, unknown names, and ambiguous defaults have stable integration codes',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'ERR-002',
        guarantee: 'Native FilesError identity and code survive initialization failures',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'NUXT-001',
        guarantee: 'Real Nuxt runtime routes receive the configured Files instances',
        source: 'test/nuxt/suite.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'NUXT-002',
        guarantee: 'Native Vue composable auto-imports compile and build',
        source: 'test/nuxt/vue.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'NITRO-001',
        guarantee: 'Nitro v2/v3 prepare, typecheck, build, and serve the Files route',
        source: 'test/nitro/suite.ts',
        job: 'test-nitro2',
    },
    {
        id: 'DEV-001',
        guarantee: 'Production, module opt-out, and disabled Nuxt DevTools disable the DevFrame',
        source: 'test/nuxt/devtools.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'DEV-002',
        guarantee: 'DevTools v3 registers a single iframe for the shared UI',
        source: 'test/nuxt/devtools.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'DEV-003',
        guarantee: 'DevTools v4 registers the native DevFrame-ready host',
        source: 'test/nuxt/devtools.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'DEV-004',
        guarantee: 'The development host serves the shared UI and the actual configured registry snapshot',
        source: 'test/nuxt/nuxt4-devframe.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'BUNDLE-001',
        guarantee: 'Server-only Nuxt does not include files-sdk/vue',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'BUNDLE-002',
        guarantee: 'Production excludes DevFrame and development host code',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'BUNDLE-003',
        guarantee: 'fs consumers do not ship external AWS/Azure/Google SDK packages',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'BUNDLE-004',
        guarantee: 'A versioning-only import excludes unrelated built-in plugin entrypoints',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'BUNDLE-005',
        guarantee: 'Standalone Nitro excludes Nuxt Kit, DevTools, and Files Vue runtime',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'BUNDLE-006',
        guarantee: 'Deployment sizes are measured; established Nuxt output budgets are enforced',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'SEC-001',
        guarantee: 'Dummy secrets are absent from production and generated outputs',
        source: 'test/bundle/bundle.test.ts',
        job: 'test-size',
    },
    {
        id: 'SEC-002',
        guarantee: 'DevFrame snapshots contain only safe metadata and diagnostics',
        source: 'test/unit/registry.test.ts',
        job: 'unit',
    },
    {
        id: 'SEC-003',
        guarantee: 'The packed artifact contains no dummy secret',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'PKG-001',
        guarantee: 'Required JavaScript and declaration entrypoints are packed',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'PKG-002',
        guarantee: 'The tarball contains only distribution files and public package metadata',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'PKG-003',
        guarantee: 'Exports and dependency/optional-peer boundaries are explicit',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'PKG-004',
        guarantee:
            'Fresh Nuxt/Nitro consumers install the tarball, typecheck, build, and run with bundle/security boundaries intact',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'PKG-005',
        guarantee: 'publint and ATTW validate the actual tarball',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'DOCS-001',
        guarantee: 'Canonical fixture examples and native public types compile against generated declarations',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'DOCS-002',
        guarantee: 'Packed public APIs, generated auto-imports, and configuration fields retain hover documentation',
        source: 'test/nuxt/nuxt4-generated-types.test.ts',
        job: 'test-nuxt4',
    },
    {
        id: 'REL-001',
        guarantee: 'Consumer verification leaves the release tarball SHA-256 unchanged',
        source: 'test/consumer/packed.test.ts',
        job: 'test-consumer',
    },
    {
        id: 'REL-002',
        guarantee: 'ci-ok directly gates every blocking job, and release verifies the tarball before publishing',
        source: 'test/unit/contracts.test.ts',
        job: 'unit',
    },
]
