export const defaultFilesIcons = {
    check: 'i-lucide-check',
    chevronRight: 'i-lucide-chevron-right',
    close: 'i-lucide-x',
    copy: 'i-lucide-copy',
    download: 'i-lucide-download',
    ellipsis: 'i-lucide-ellipsis',
    error: 'i-lucide-circle-x',
    file: 'i-lucide-file',
    folder: 'i-lucide-folder',
    folderOpen: 'i-lucide-folder-open',
    history: 'i-lucide-history',
    home: 'i-lucide-house',
    link: 'i-lucide-link',
    loading: 'i-lucide-loader-circle',
    move: 'i-lucide-folder-input',
    refresh: 'i-lucide-refresh-cw',
    rename: 'i-lucide-pencil',
    restore: 'i-lucide-rotate-ccw',
    search: 'i-lucide-search',
    success: 'i-lucide-circle-check',
    trash: 'i-lucide-trash-2',
    upload: 'i-lucide-upload',
} as const

export type FilesIconName = keyof typeof defaultFilesIcons
