export interface ProviderFactories {
    akamai: typeof import('files-sdk/akamai').akamai
    alibaba: typeof import('files-sdk/alibaba').alibaba
    appwrite: typeof import('files-sdk/appwrite').appwrite
    archil: typeof import('files-sdk/archil').archil
    azure: typeof import('files-sdk/azure').azure
    'backblaze-b2': typeof import('files-sdk/backblaze-b2').backblazeB2
    box: typeof import('files-sdk/box').box
    'bun-s3': typeof import('files-sdk/bun-s3').bunS3
    'bunny-storage': typeof import('files-sdk/bunny-storage').bunnyStorage
    cloudinary: typeof import('files-sdk/cloudinary').cloudinaryAdapter
    convex: typeof import('files-sdk/convex').convex
    'digitalocean-spaces': typeof import('files-sdk/digitalocean-spaces').digitaloceanSpaces
    dropbox: typeof import('files-sdk/dropbox').dropbox
    exoscale: typeof import('files-sdk/exoscale').exoscale
    filebase: typeof import('files-sdk/filebase').filebase
    'firebase-storage': typeof import('files-sdk/firebase-storage').firebaseStorage
    fs: typeof import('files-sdk/fs').fs
    ftp: typeof import('files-sdk/ftp').ftp
    gcs: typeof import('files-sdk/gcs').gcs
    'google-drive': typeof import('files-sdk/google-drive').googleDrive
    hetzner: typeof import('files-sdk/hetzner').hetzner
    'ibm-cos': typeof import('files-sdk/ibm-cos').ibmCos
    'idrive-e2': typeof import('files-sdk/idrive-e2').idriveE2
    memory: typeof import('files-sdk/memory').memory
    minio: typeof import('files-sdk/minio').minio
    neon: typeof import('files-sdk/neon').neon
    'netlify-blobs': typeof import('files-sdk/netlify-blobs').netlifyBlobs
    onedrive: typeof import('files-sdk/onedrive').onedrive
    'oracle-cloud': typeof import('files-sdk/oracle-cloud').oracleCloud
    ovhcloud: typeof import('files-sdk/ovhcloud').ovhcloud
    pocketbase: typeof import('files-sdk/pocketbase').pocketbase
    r2: typeof import('files-sdk/r2').r2
    rustfs: typeof import('files-sdk/rustfs').rustfs
    s3: typeof import('files-sdk/s3').s3
    's3-fetch': typeof import('files-sdk/s3-fetch').s3Fetch
    scaleway: typeof import('files-sdk/scaleway').scaleway
    sftp: typeof import('files-sdk/sftp').sftp
    sharepoint: typeof import('files-sdk/sharepoint').sharepoint
    storj: typeof import('files-sdk/storj').storj
    supabase: typeof import('files-sdk/supabase').supabase
    tencent: typeof import('files-sdk/tencent').tencent
    tigris: typeof import('files-sdk/tigris').tigris
    uploadthing: typeof import('files-sdk/uploadthing').uploadthing
    'vercel-blob': typeof import('files-sdk/vercel-blob').vercelBlob
    vultr: typeof import('files-sdk/vultr').vultr
    wasabi: typeof import('files-sdk/wasabi').wasabi
    webdav: typeof import('files-sdk/webdav').webdav
    yandex: typeof import('files-sdk/yandex').yandex
}
