import { defineConfig } from 'tsdown'

export default defineConfig([
    {
        attw: { level: 'error', profile: 'esm-only' },
        clean: true,
        copy: [
            { from: 'src/devtools/client/index.html', to: 'dist/devtools/client' },
            { from: '../../README.md', to: '.' },
        ],
        deps: {
            dts: { neverBundle: true },
            neverBundle: true,
            onlyImport: [
                '@nuxt/kit',
                '@nuxt/devtools-kit',
                'devframe',
                'files-sdk',
                'jiti',
                'node:fs',
                'node:fs/promises',
                'node:path',
                'node:url',
            ],
        },
        dts: true,
        entry: {
            config: 'src/config.ts',
            module: 'src/module.ts',
            nitro: 'src/nitro.ts',
            plugins: 'src/plugins.ts',
            'plugins/versioning': 'src/plugin-versioning.ts',
            runtime: 'src/runtime.ts',
            'devtools/files-read': 'src/devtools/files-read.ts',
            'devtools/files-write': 'src/devtools/files-write.ts',
            'devtools/nuxt-v3-handler': 'src/devtools/nuxt-v3-handler.ts',
            'devtools/snapshot': 'src/devtools/snapshot.ts',
        },
        exports: false,
        format: ['esm'],
        platform: 'neutral',
        publint: true,
        sourcemap: true,
        unbundle: true,
    },
    {
        clean: false,
        deps: {
            alwaysBundle: [/^(?:birpc|devframe|files-sdk|nostics|p-map|ufo)(?:\/|$)/u],
            onlyBundle: [/^(?:birpc|devframe|files-sdk|nostics|p-map|ufo)(?:\/|$)/u],
        },
        dts: false,
        entry: { app: 'src/devtools/client/app.ts' },
        format: ['esm'],
        minify: true,
        outDir: 'dist/devtools/client',
        platform: 'browser',
        sourcemap: false,
    },
])
