import { defineConfig } from 'tsdown'

export default defineConfig([
    {
        attw: { level: 'error', profile: 'esm-only' },
        clean: true,
        copy: [
            { from: 'src/ui/components/*.vue', to: 'dist/ui/components' },
            { from: 'src/ui/integration/*.vue', to: 'dist/ui/integration' },
            { from: 'src/ui/controls/nuxt-ui/*.vue', to: 'dist/ui/controls/nuxt-ui' },
            { from: 'src/ui/controls/standalone/*.vue', to: 'dist/ui/controls/standalone' },
            { from: 'src/ui/styles.css', to: 'dist/ui' },
            { from: 'src/ui/styles.standalone.css', to: 'dist/ui' },
            { from: '../../README.md', to: '.' },
            { from: '../../LICENSE', to: '.' },
        ],
        deps: {
            dts: { neverBundle: true },
            neverBundle: true,
            onlyImport: [
                '@iconify/vue',
                '@nuxt/icon',
                '@nuxt/kit',
                '@nuxt/devtools-kit',
                '@nuxt/ui',
                '@tailwindcss/vite',
                'devframe',
                'files-sdk',
                'jiti',
                'nuxt',
                'reka-ui',
                'tailwind-variants',
                'tailwindcss',
                'vue',
                'node:crypto',
                'node:fs',
                'node:fs/promises',
                'node:module',
                'node:path',
                'node:url',
            ],
        },
        dts: true,
        entry: {
            config: 'src/config.ts',
            module: 'src/module.ts',
            nitro: 'src/nitro.ts',
            runtime: 'src/runtime.ts',
            'runtime/internal': 'src/runtime/internal.ts',
            'integration/config': 'src/integration/config.ts',
            'devtools/files-read': 'src/devtools/files-read.ts',
            'devtools/files-write': 'src/devtools/files-write.ts',
            'devtools/nuxt-v3-handler': 'src/devtools/nuxt-v3-handler.ts',
            'devtools/snapshot': 'src/devtools/snapshot.ts',
            'devtools/token': 'src/devtools/token.ts',
            'ui/icons': 'src/ui/icons.ts',
            'ui/locale': 'src/ui/locale.ts',
            'ui/runtime/actions': 'src/ui/runtime/actions.ts',
            'ui/runtime/component-props': 'src/ui/runtime/component-props.ts',
            'ui/runtime/context': 'src/ui/runtime/context.ts',
            'ui/runtime/locale': 'src/ui/runtime/locale.ts',
            'ui/runtime/nuxt-plugin': 'src/ui/runtime/nuxt-plugin.ts',
            'ui/runtime/nuxt-ui-plugin': 'src/ui/runtime/nuxt-ui-plugin.ts',
            'ui/runtime/theme': 'src/ui/runtime/theme.ts',
            'ui/runtime/themes': 'src/ui/runtime/themes.ts',
            'ui/runtime/utils': 'src/ui/runtime/utils.ts',
        },
        exports: false,
        format: ['esm'],
        platform: 'neutral',
        publint: true,
        sourcemap: true,
        unbundle: true,
    },
])
